= 1n9yun's Todo App REST API
정인균;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-curl-response-title: Example response

[[overView]]
= OverView

개요개요

[[overview-errors]]
== Errors

에러 응답이 발생했을 때 (상태 코드 >= 400), 본문에 해당 문제를 기술한 JSON 객체가 담겨있다. 에러 객체는 다음의 구조를 따른다.

...

[[resources]]
= Resources

[[resources-index]]
== Index

서비스 진입접을 제공한다.

[[resources-index-access]]
=== Index 조회
`GET` 요청을 사용하여 인덱스에 접근할 수 있다.

operation::index[snippets='curl-request,http-request,response-body,http-response,links']

[[resources-todos]]
== Todo

Todo 리소스는 Todo를 만들거나 조회할 때 사용한다.

[[resources-todos-list]]
=== Todo 목록 조회
==== 단일 조회
하나의 Todo를 조회

operation::query-todo[snippets='curl-request,http-request,request-headers,request-body,response-fields,http-response,response-headers,response-body,links']

==== 전체 조회
로그인한 회원이 가지고 있는 Todo의 리스트를 조회

operation::query-todos[snippets='curl-request,http-request,request-headers,request-body,response-fields,http-response,response-headers,response-body,links']

[[resources-todos-create]]
=== Todo 생성
`POST` 요청을 사용해서 새 Todo를 만들 수 있다.

operation::create-todo[snippets='request-fields,curl-request,http-request,request-headers,request-body,response-fields,http-response,response-headers,response-body,links']